project_id = "ivonodtszlrorgdcisyb"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.assign-demo-role]
verify_jwt = false

[functions.demo-auto-login]
verify_jwt = false

[functions.demo-otp-signup]
verify_jwt = false
